<?php
/**
 * This file is generated by the "yii asset" command.
 * DO NOT MODIFY THIS FILE DIRECTLY.
 * @version 2015-04-05 23:59:16
 */
return [];
<<<TEST>>>

"GlobalCode":{
  "NamingContext":{},
  "JumpStmt":{"Type":"Return","ArrayEx":{}}
}
